default:
  image: cypress/base:10
  
before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .npm
    - cache
    - node_modules

build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  needs: [build]
  stage: test
  script:
    - CI=true npm test

end-to-end test:
  stage: test
  needs: [build]
  script:
    - npm run test:e2e
  artifacts:
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 30 day

staging:
  needs: [test]
  stage: deploy
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
    - CYPRESS_BASE_URL=https://${HEROKU_APP_STAGING}.herokuapp.com npm run cypress:run
  artifacts:
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 30 day

production:
  stage: deploy
  needs: [test]
  when: manual
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
  - main