stages:
  - build
  - test
  - deploy

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build

unit test:
  image: node:latest
  needs: ["build"]
  stage: test
  script:
    - CI=true npm test


end-to-end test:
  image: cypress/base:10
  needs: ["build"]
  stage: test
  script:
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

heroku:
  needs: ["test"]
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api_key=$HEROKU_API_KEY