default:
  image: mhart/alpine-node:10
  
before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - build
  - test
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules


build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  needs: [build]
  stage: test
  script:
    - CI=true npm test


end-to-end test:
  image: cypress/base:10
  stage: test
  needs: [build]
  script:
    - npm run test:e2e
  artifacts:
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 30 day
  
heroku:
  stage: deploy
  needs: [test]
  script:
    - npm i fsevents@latest -f --save-optional
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api_key=$HEROKU_API_KEY